#!/usr/bin/env bash
#
# install-cai-vibe.sh
#
# One-time installer for Mistral Vibe + Cloudera AI Inference (OpenAI API direct).
#
#   1. Fail fast if curl is missing
#   2. Install Mistral Vibe CLI if needed
#   3. Prompt for CAI endpoint URL + JWT; validate connection
#   4. Install launch script → ~/.local/bin/vibe-cai
#
# After install, run:  vibe-cai
#
# Unattended:
#   CAI_NONINTERACTIVE=1 CAI_API_BASE=... CAI_CDP_TOKEN=... ./install-cai-vibe.sh

set -Eeuo pipefail
IFS=$' \t\n'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CAI_HOME_DEFAULT="${HOME}/.vibe/cai-inference"
CAI_HOME="${CAI_INSTALL_HOME:-$CAI_HOME_DEFAULT}"
LAUNCH_NAME="vibe-cai"
LOCAL_BIN="${HOME}/.local/bin"
INSTALLED_LAUNCH="${LOCAL_BIN}/${LAUNCH_NAME}"

log() { printf '%s\n' "$*" >&2; }
die() { log "ERROR: $*"; exit 1; }

is_interactive() {
  [ -t 0 ] && [ -t 1 ] && [ -z "${CAI_NONINTERACTIVE:-}" ]
}

have_cmd() { command -v "$1" >/dev/null 2>&1; }

confirm() {
  local prompt="$1" default="${2:-y}" reply hint
  if [ "$default" = "y" ]; then hint="[Y/n]"; else hint="[y/N]"; fi
  if ! is_interactive; then
    [ "$default" = "y" ] && return 0 || return 1
  fi
  printf '%s %s: ' "$prompt" "$hint" >&2
  read -r reply || reply=""
  [ -z "$reply" ] && reply="$default"
  case "$reply" in y|Y|yes|Yes) return 0 ;; *) return 1 ;; esac
}

check_requirements() {
  log ""
  log "=== Step 1/5 — Checking requirements ==="
  have_cmd curl || die "curl is required. Install curl and re-run this script."
  log "  curl: $(command -v curl)"
  log "  Requirements OK."
}

ensure_mistral_vibe() {
  log ""
  log "=== Step 2/5 — Mistral Vibe CLI ==="

  if have_cmd vibe; then
    log "  Mistral Vibe: $(vibe --version 2>/dev/null | head -1 || echo installed)"
    return 0
  fi

  log "  Mistral Vibe (vibe) not found."
  if is_interactive && confirm "Install Mistral Vibe now (official install script)?" "y"; then
    curl -fsSL https://raw.githubusercontent.com/mistralai/mistral-vibe/main/scripts/install.sh | bash
    export PATH="${HOME}/.local/bin:${PATH}"
  elif have_cmd uv; then
    log "  Trying: uv tool install mistral-vibe"
    uv tool install mistral-vibe
    export PATH="${HOME}/.local/bin:${PATH}"
  fi

  if have_cmd vibe; then
    log "  Mistral Vibe: $(vibe --version 2>/dev/null | head -1 || echo installed)"
  else
    die "Mistral Vibe is required. Install: https://github.com/mistralai/mistral-vibe"
  fi
}

install_launcher() {
  log ""
  log "=== Step 3/5 — Installing launcher ==="

  mkdir -p "${CAI_HOME}/lib" "${CAI_HOME}/bin" "$LOCAL_BIN"

  cp "${SCRIPT_DIR}/lib/cai-common.sh" "${CAI_HOME}/lib/cai-common.sh"
  cp "${SCRIPT_DIR}/vibe-cai-launch.sh" "${CAI_HOME}/bin/vibe-cai-launch.sh"
  chmod +x "${CAI_HOME}/bin/vibe-cai-launch.sh"

  cat >"$INSTALLED_LAUNCH" <<EOF
#!/usr/bin/env bash
exec "${CAI_HOME}/bin/vibe-cai-launch.sh" "\$@"
EOF
  chmod +x "$INSTALLED_LAUNCH"

  cat >"${CAI_HOME}/install.env" <<EOF
# Generated by install-cai-vibe.sh — do not edit
CAI_HOME=${CAI_HOME}
CAI_INSTALL_SCRIPT=${SCRIPT_DIR}/install-cai-vibe.sh
CAI_INSTALL_ENV=${CAI_HOME}/install.env
EOF
  chmod 600 "${CAI_HOME}/install.env"

  log "  Library:  ${CAI_HOME}/lib/cai-common.sh"
  log "  Launcher: ${INSTALLED_LAUNCH}"
}

ensure_local_bin_on_path() {
  case ":${PATH}:" in
    *":${LOCAL_BIN}:"*) return 0 ;;
  esac
  if is_interactive && confirm "Add ${LOCAL_BIN} to PATH in this shell session?" "y"; then
    export PATH="${LOCAL_BIN}:${PATH}"
  fi
  if is_interactive && confirm "Add ${LOCAL_BIN} to ~/.zshrc or ~/.bashrc permanently?" "y"; then
    local profile=""
    [ -f "${HOME}/.zshrc" ] && profile="${HOME}/.zshrc"
    [ -z "$profile" ] && [ -f "${HOME}/.bashrc" ] && profile="${HOME}/.bashrc"
    if [ -n "$profile" ] && ! grep -qF "${LOCAL_BIN}" "$profile" 2>/dev/null; then
      printf '\n# Mistral Vibe + CAI Inference launcher\nexport PATH="%s:$PATH"\n' "$LOCAL_BIN" >>"$profile"
      log "  Added PATH to ${profile}"
    fi
  fi
}

configure_endpoint() {
  log ""
  log "=== Step 4/5 — Configure Cloudera AI Inference endpoint ==="

  CAI_HOME="$CAI_HOME"
  # shellcheck disable=SC1090
  source "${CAI_HOME}/lib/cai-common.sh"

  cai_load_config

  if [ -z "${CAI_API_BASE:-}" ] || [ -z "${CAI_CDP_TOKEN:-}" ]; then
    cai_prompt_user_config
  else
    CAI_API_BASE="$(cai_normalize_url "$CAI_API_BASE" "$CAI_CDP_TOKEN")"
    [ -n "${CAI_MODEL_NAME:-}" ] || CAI_MODEL_NAME="$(cai_fetch_model_name "$CAI_API_BASE" "$CAI_CDP_TOKEN")"
    cai_save_config
    cai_sync_vibe_files
  fi

  log "  Validating connection ..."
  cai_validate_connection "$CAI_API_BASE" "$CAI_CDP_TOKEN"
  log "  Connection OK."
  log "  Model: ${CAI_MODEL_NAME}"
  log "  Config: ${CONFIG_FILE}"
  log "  Vibe config: ${VIBE_CONFIG}"
}

finish() {
  log ""
  log "=== Step 5/5 — Done ==="
  log ""
  log "============================================"
  log "  Install complete!"
  log ""
  log "  Launch Mistral Vibe anytime:"
  log "    vibe-cai"
  log ""
  log "  Reconfigure URL/token:"
  log "    vibe-cai --reconfigure"
  log ""
  log "  Isolated Vibe home (config + JWT):"
  log "    ${CAI_HOME}/"
  log "============================================"

  if is_interactive && confirm "Launch Mistral Vibe now?" "y"; then
    exec "$INSTALLED_LAUNCH"
  fi
}

main() {
  case "${1:-}" in
    -h|--help)
      sed -n '2,16p' "$0" >&2
      exit 0
      ;;
  esac

  check_requirements
  ensure_mistral_vibe
  install_launcher
  ensure_local_bin_on_path
  configure_endpoint
  finish
}

main "$@"
